// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/site-redesign/EditorialLuxury.tsx": () => import("../components/mockups/site-redesign/EditorialLuxury.tsx"),
  "./components/mockups/site-redesign/MidnightNoir.tsx": () => import("../components/mockups/site-redesign/MidnightNoir.tsx"),
  "./components/mockups/site-redesign/SoftMinimal.tsx": () => import("../components/mockups/site-redesign/SoftMinimal.tsx")
};
